### ISSUE TITLE
ExceptionInInitializerError while registering command

### ISSUE THREAD

**Issue by ArnyminerZ** [JorelAli/1.13-Command-API#124]
I'm trying to use the API, but when trying to register the command I get `java.lang.ExceptionInInitializerError`. Any ideas of what could I be doing wrong? I'm using Kotlin BTW.
Here's the piece of code I'm using.
```kotlin
CommandAPICommand("main")
    .withArguments(with(linkedMapOf<String, Argument>()) {
        put("type", StringArgument().overrideSuggestions("reload", "autosave", "resources"))
        this
    })
    .withPermission(CommandPermission.fromString("command.main"))
    .executes(object : CommandExecutor {
        override fun run(sender: CommandSender, args: Array<out Any>) {
            ...
        }
    })
    .register()
```
This is the full error thrown:
```
java.lang.ExceptionInInitializerError: null
        at dev.jorel.commandapi.CommandAPICommand.register(CommandAPICommand.java:208) ~[?:?]
        at com.arnyminerz.minecraft.plugin.alcoas.commands.AlcoasCommand.<init>(AlcoasCommand.kt:86) ~[?:?]
        at com.arnyminerz.minecraft.plugin.alcoas.Alcoas.onEnable(Main.kt:282) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-0509002-6b95d59]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot.jar:git-Spigot-0509002-6b95d59]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:git-Spigot-0509002-6b95d59]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot.jar:git-Spigot-0509002-6b95d59]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot.jar:git-Spigot-0509002-6b95d59]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438) ~[spigot.jar:git-Spigot-0509002-6b95d59]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot.jar:git-Spigot-0509002-6b95d59]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[spigot.jar:git-Spigot-0509002-6b95d59]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-0509002-6b95d59]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at dev.jorel.commandapi.CommandAPIHandler.<init>(CommandAPIHandler.java:122) ~[?:?]
        at dev.jorel.commandapi.CommandAPI.<clinit>(CommandAPI.java:26) ~[?:?]
        ... 13 more
```

Thank you very much in advance.

**Comment by ArnyminerZ** [comment]
Ok, resolved it by adding the plugin to `depend` in plugin.yml as follows:
```yml
depend: [CommandAPI]
```
Also I installed the `CommandAPI` plugin in my server, as well as the `NBT API` plugin.
