### ISSUE TITLE
Server unable to load function with custom command

### ISSUE THREAD

**Issue by Comeza** [JorelAli/1.13-Command-API#68]
**CommandAPI version**
CommandAPI 2.2 on Paper-166 (1.14.4)
also tried it with a Spigot version from [GetBukkit.org](https://getbukkit.org/download/spigot)

**Describe the bug**
The server is unable load a mcfunction file with a custom command.
The command it self works as intended.

**My code**
(Copied from [documentation](https://jorelali.github.io/1.13-Command-API/functions.html))
```java
@Override
    public void onLoad() {
        //Commands which will be used in Minecraft functions are registered here

        CommandAPI.getInstance().register("killall", new LinkedHashMap<>(), (sender, args) -> {
            //Kills all enemies in all worlds
            Bukkit.getWorlds()
                    .forEach(w -> w.getLivingEntities()
                            .forEach(e -> e.setHealth(0))
                    );
        });
    }
```

**Error**

```
[23:32:31 ERROR]: Couldn't load function at test:functions/with.mcfunction
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown command at position 0: <--[HERE]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_191]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_191]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown command at position 0: <--[HERE]
	at net.minecraft.server.v1_14_R1.CustomFunction.a(CustomFunction.java:77) ~[patched_1.14.4.jar:git-Paper-166]
	at net.minecraft.server.v1_14_R1.CustomFunctionData.lambda$a$2(CustomFunctionData.java:168) ~[patched_1.14.4.jar:git-Paper-166]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_191]
	... 6 more
```

Log-file:
[latest.log](https://github.com/JorelAli/1.13-Command-API/files/3489311/latest.log)

**Comment by Minenash** [comment]
Not the dev, but can you upload the .mcfunction file?

**Comment by JorelAli** [comment]
## Issue Status
Firstly, sorry for waiting SO LONG before actually responding or doing something about it. I've been busy with other work, so I hope you'll forgive the delay.

I've done my initial testing to get a clearer idea of what the issue is and can confirm that 1.14.4 servers cannot load a custom command from a .mcfunction command (@Minenash Nice of you to ask for the .mcfunction file, but this is no longer necessary now knowing the nature of the issue.)

When I did my initial testing, the error I got in the console was different, but I believe it links to the same issue.

## So what's the problem?
Minecraft 1.14.3 changed how functions in .mcfunction files are evaluated during the server startup sequence. When a command is given to the CommandAPI, it runs a permission check to ensure that the sender of the command can run the command. In order to run the permission check, it retrieves the `CommandSender` object that you all know and love from the Bukkit API.

Prior to 1.14.3, the `CommandSender` object would be returned (even if it was like a "dummy" commandsender), however now, it throws an `UnsupportedOperationException`. Which of course, makes sense - the startup sequence is trying to evaluate each command to check its validity, but the CommandAPI can't do that if the command sender is non-existent, which is indeed the case.

## When will this be fixed?
~~No idea.~~ Actually, right now. During the process of writing this response, I've resolved the issue.

**Comment by Minenash** [comment]
The original reason I asked is when I write my function files, there's often a 0-width character at the beginning of the file, and this has happen to some people I know. Glad it had been resolved, though!
