### ISSUE TITLE
Registering a command with no arguments throws index out of bound error

### ISSUE THREAD

**Issue by Combustible** [JorelAli/1.13-Command-API#7]
Sample code. This command has a variant with and without arguments - the without-arguments variant sends you a list of valid targets. 

```java
        LinkedHashMap<String, Argument> arguments = new LinkedHashMap<>();
        CommandAPI.getInstance().register(command,
                                          perms,
                                          arguments,
                                          (sender, args) -> {
                                              if (sender instanceof Player) {
                                                  getServerList(plugin, sender, (Player)sender);
                                              } else {
                                                  error(sender, "No-argument variant can only be run by players");
                                              }
                                          }
        );
```

```
java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:422)
    at java.util.ArrayList.get(ArrayList.java:435)
    at io.github.jorelali.commandapi.api.SemiReflector.register(SemiReflector.java:322)
    at io.github.jorelali.commandapi.api.CommandAPI.register(CommandAPI.java:86)
    at com.playmonumenta.plugins.rawcommands.TransferServer.register(TransferServer.java:33)
    at com.playmonumenta.plugins.Plugin.onEnable(Plugin.java:199)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
    at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584)
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546)
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424)
    at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
    at java.lang.Thread.run(Thread.java:748)```

**Comment by Combustible** [comment]
Works great, thanks.
